export type IntelligenceDomain='AFIS'|'ABL'; export type FeatureQuality='HIGH'|'MEDIUM'|'LOW';
export interface FeatureRecord{featureId:string;name:string;value:number;normalizedValue?:number;observedAt:string;sourceEventIds:string[];quality:FeatureQuality;deterministic:boolean}
export type SignalType='MOMENTUM'|'MEAN_REVERSION'|'SPREAD'|'IMBALANCE'|'ARBITRAGE'|'ANOMALY'|'ODDS_MOVEMENT'|'CROSS_BOOK_DISCREPANCY'|'SPORTS_VALUE'|'LIQUIDITY_STRESS'|'VOLATILITY_EXPANSION'|'FUNDING_ARBITRAGE';export type Direction='LONG'|'SHORT'|'NEUTRAL'|'YES'|'NO';
export interface SignalRecord{signalId:string;type:SignalType;direction:Direction;strength:number;confidence:number;generatedAt:string;expiresAt:string;sourceFeatureIds:string[];explanation:string}
export type FairValueMethod='REFERENCE_PRICE'|'VENUE_CONSENSUS'|'WEIGHTED_ENSEMBLE'|'MODEL_ESTIMATE'|'ARBITRAGE_BOUND';export interface FairValueRecord{fairValueId:string;value:number;lowerBound?:number;upperBound?:number;methodology:FairValueMethod;confidence:number;sourceIds:string[];calculatedAt:string}
export type EdgeMethod='PRICE_DIFFERENCE'|'PROBABILITY_DIFFERENCE'|'ARBITRAGE_MARGIN'|'MODEL_VS_MARKET';export interface EdgeRecord{grossEdge:number;netEdge?:number;expectedValue?:number;methodology:EdgeMethod;confidence:number;calculatedAt:string}
export interface ConfidenceRecord{score:number;level:'VERY_LOW'|'LOW'|'MEDIUM'|'HIGH'|'VERY_HIGH';supportingEvidence:string[];negativeEvidence:string[];calibrated:boolean}
export type Regime='QUIET'|'NORMAL'|'TRENDING'|'MEAN_REVERTING'|'HIGH_VOLATILITY'|'LIQUIDITY_STRESS'|'DISLOCATED'|'STABLE'|'EARLY_MARKET'|'ACTIVE_MOVEMENT'|'LATE_MARKET'|'HIGH_DISPERSION'|'CONFLICTED';export interface RegimeRecord{regime:Regime;confidence:number;reason:string}
export type AnomalyType='PRICE_DISLOCATION'|'ODDS_DISLOCATION'|'SPREAD_EXPANSION'|'LIQUIDITY_DROP'|'SOURCE_CONFLICT'|'TIMESTAMP_ANOMALY'|'DATA_QUALITY';export interface AnomalyRecord{anomalyId:string;type:AnomalyType;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';score:number;description:string;sourceIds:string[]}
export interface EvidenceRecord{evidenceId:string;type:'EVENT'|'FEATURE'|'SIGNAL'|'VENUE'|'MODEL'|'CONSENSUS';sourceId:string;quality:number;freshness:number;relevance:number;reliability:number;timestamp:string}
export type IntelligenceStatus='GENERATED'|'VALIDATED'|'STALE'|'CONFLICTED'|'REJECTED'|'EXPIRED';export interface IntelligenceRecord{intelligenceId:string;domain:IntelligenceDomain;opportunityId?:string;subject:{venue?:string;market:string;instrument?:string;selection?:string};observedAt:string;expiresAt:string;features:FeatureRecord[];signals:SignalRecord[];fairValue?:FairValueRecord;edge?:EdgeRecord;confidence:ConfidenceRecord;regime?:RegimeRecord;anomalies:AnomalyRecord[];evidence:EvidenceRecord[];status:IntelligenceStatus;correlationId:string;traceId:string;schemaVersion:'oship.intelligence.v1'}
export interface IntelligenceEligibility{eligible:boolean;reasons:string[];requiresRefresh:boolean;requiresAegisReview:boolean}
export interface IntelligenceConfig{minConfidence:number;staleAfterMs:number;conflictTolerance:number;anomalyThreshold:number;arbitrageMinEdge:number;signalWeights:Record<string,number>;evidenceWeights:{reliability:number;freshness:number;relevance:number;consistency:number}}
export const DEFAULT_INTELLIGENCE_CONFIG:IntelligenceConfig={minConfidence:.55,staleAfterMs:300000,conflictTolerance:.02,anomalyThreshold:.7,arbitrageMinEdge:.001,signalWeights:{},evidenceWeights:{reliability:.3,freshness:.25,relevance:.25,consistency:.2}};
export function bounded(n:number){if(!Number.isFinite(n))throw new Error('non-finite intelligence value');return Math.max(0,Math.min(1,n))}export function validateConfig(c:IntelligenceConfig){if(c.minConfidence<0||c.minConfidence>1||c.staleAfterMs<0||c.conflictTolerance<0||c.anomalyThreshold<0||c.anomalyThreshold>1)throw new Error('invalid intelligence config');return c}
